apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-store
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cert-manager
  name: eso-store
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: eso-store
    namespace: cert-manager
roleRef:
  kind: Role
  name: eso-store
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default-cert
  annotations:
    # argocd.argoproj.io/sync-wave: "60"
spec:
  provider:
    kubernetes:
      remoteNamespace: cert-manager
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: cert-manager
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-store
          namespace: cert-manager