sources:
  - service
  - ingress
provider: aws
txtOwnerId: cnoe-external-dns
registry: txt
interval: 2m
policy: sync
extraArgs:
  - --aws-zone-type=public
  - --aws-zones-cache-duration=1h
domainFilters:
  - advaitt.people.aws.dev