apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-aws-runtime-config
spec:
  deploymentTemplate:
    spec:
      selector: {} # Required to specify by CRD spec
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - --debug
                - --enable-management-policies
          securityContext:
            fsGroup: 2000

