apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cnoe-ref-impl
  region: us-west-2
  version: "1.28"
managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.large
    minSize: 3
    maxSize: 6
    desiredCapacity: 4
    volumeSize: 100
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      role: general-purpose
iam:
  withOIDC: true
addons:
- name: aws-ebs-csi-driver
  version: "v1.28.0-eksbuild.1"
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy