apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cnoe-ref-impl
  region: us-east-1
  version: "1.29"
managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.medium
    minSize: 2
    maxSize: 6
    desiredCapacity: 3
    volumeSize: 100
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      role: general-purpose
iam:
  withOIDC: true
addons:
- name: aws-ebs-csi-driver
  version: "v1.29.0-eksbuild.1"
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy