apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: keycloak-oidc
    template:
      data:
        ARGO_WORKFLOWS_CLIENT_ID: "argo-workflows"
        ARGO_WORKFLOWS_CLIENT_SECRET: '{{ .clientSecret }}'
  data:
  - secretKey: clientSecret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: keycloak-clients
      property: ARGO_WORKFLOWS_CLIENT_SECRET
