---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloak-config
    template:
      data:
        # ARGO_CD_SESSION_URL: "http://argocd-server.argocd.svc.cluster.local:443{{ if .pathRouting }}/argocd{{ end }}/api/v1/session"
        KEYCLOAK_URL: "http://keycloak.keycloak.svc.cluster.local{{ if .pathRouting }}/keycloak{{ end }}"
        POSTGRES_PASSWORD: "{{ .postgresPassword }}"
        KEYCLOAK_ADMIN_PASSWORD: "{{ .keycloakAdminPassword }}"
        USER1_PASSWORD:  "{{ .keycloakUserPassword }}"
        ARGO_CD_URL: "{{ if .pathRouting }}{{ .domainName }}/argocd{{ else }}argocd.{{ .domainName }}{{ end }}"
        BACKSTAGE_URL: "{{ if .pathRouting }}{{ .domainName }}{{ else }}backstage.{{ .domainName }}{{ end }}"
        ARGO_WORKFLOW_URL: "{{ if .pathRouting }}{{ .domainName }}/argo-workflows{{ else }}argo-workflows.{{ .domainName }}{{ end }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "postgres-keycloak-password"
    rewrite:
    - transform:
        template: "postgresPassword"
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "postgres-keycloak-password"
    rewrite:
    - transform:
        template: "keycloakAdminPassword"
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "keycloak-user-password"
    rewrite:
    - transform:
        template: "keycloakUserPassword"
  data:
  - secretKey: domainName
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: domain
  - secretKey: pathRouting
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: path_routing
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-keycloak-password
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "/-+"
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-user-password
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-" # No Special character as Argo CD does not support it.
  noUpper: false
  allowRepeat: true
