---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: keycloak-config
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: keycloak.postgres-password
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: keycloak.admin-password
      

# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: postgresql-config
#   namespace: keycloak
# spec:
#   refreshInterval: 5m
#   secretStoreRef:
#     name: keycloak
#     kind: SecretStore
#   target:
#     name: postgresql-config
#     creationPolicy: Owner
#   data:
#     - secretKey: POSTGRES_DB
#       remoteRef:
#         key: cnoe/keycloak/config
#         property: POSTGRES_DB
#     - secretKey: POSTGRES_PASSWORD
#       remoteRef:
#         key: cnoe/keycloak/config
#         property: POSTGRES_PASSWORD
#     - secretKey: POSTGRES_USER
#       remoteRef:
#         key: cnoe/keycloak/config
#         property: POSTGRES_USER
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: keycloak-user-config
#   namespace: keycloak
# spec:
#   refreshInterval: 5m
#   secretStoreRef:
#     name: keycloak
#     kind: SecretStore
#   target:
#     name: keycloak-user-config
#     creationPolicy: Owner
#   data:
#     - secretKey: user1-password
#       remoteRef:
#         key: cnoe/keycloak/config
#         property: user1-password
