---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  target:
    name: keycloak-config
    template:
      data:
        POSTGRES_PASSWORD: "{{ .password }}"
        KEYCLOAK_ADMIN_PASSWORD: "{{ .password }}"
        USER1_PASSWORD:  "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "postgres-password"
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "keycloak-admin-password"
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "keycloak-user-password"
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: keycloak.postgres-password
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: keycloak.admin-password
  - secretKey: USER1_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: keycloak.user1-password
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "/-+"
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-admin-password
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "/-+"
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-user-password
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "/-+"
  noUpper: false
  allowRepeat: true
