# TODO: Use ExternalSecret to create the auth token using Github App 
# Ref: https://external-secrets.io/latest/api/generator/github/
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: github-token
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/punkwalker/reference-implementation-aws"
        username: unused
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default # TODO: Remove when figured out how to avoid Diffs for CR defaults
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: argo-cd-github-token