# in-cluster ArgoCD cluster Secret for passing metadata to ApplicationSets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hub-cluster-secret
  namespace: argocd
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: hub-cluster
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          clusterClass: "control-plane"
          clusterName: '{{ .clusterName }}'
          environment: "control-plane"
          path_routing: '{{ .pathRouting }}'
          auto_mode: '{{ .autoMode }}'
        annotations:
          route53_hosted_zone_id: '{{ .route53HostedZoneID }}'
          addons_repo_url: '{{ .repoURL }}'
          addons_repo_revision: '{{ .repoRevision }}'
          addons_repo_basepath: '{{ .repoBasePath }}'
          domain: '{{ .domain }}'
      data:
        name: '{{ .clusterName }}'
        server: https://kubernetes.default.svc
  data:
  - secretKey: clusterName
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: cluster_name
  - secretKey: pathRouting
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: path_routing
  - secretKey: repoURL
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: repo.url
  - secretKey: repoRevision
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: repo.revision
  - secretKey: repoBasePath
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: repo.basepath
  - secretKey: domain
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: domain
  - secretKey: autoMode
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: auto_mode
  - secretKey: route53HostedZoneID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cnoe-ref-impl/config
      metadataPolicy: None
      property: route53_hosted_zone_id