apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    clusterClass: "control-plane"
    clusterName: "in-cluster"
    environment: "control-plane"
  annotations:
    addons_repo_url: "https://github.com/punkwalker/reference-implementation-aws"
    addons_repo_revision: ref-impl-v2
    addons_repo_basepath: "packages"
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc