apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: backstage

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-all
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-read-all
subjects:
- kind: ServiceAccount
  name: backstage
  namespace: backstage
roleRef:
  kind: ClusterRole
  name: read-all
  apiGroup: rbac.authorization.k8s.io
---
# These are needed for the argo workflow plugin to create workflows during scaffolding.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-argo-worfklows
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-argo-worfklows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-argo-worfklows
subjects:
- kind: ServiceAccount
  name: backstage
  namespace: backstage
