workflow:
  serviceAccount:
    create: false
  rbac:
    create: false
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    ingressClassName: 'nginx'
    hosts:
    - paths:
      - pathType: Prefix
    tls:
    - secretName: argo-workflows-prod-tls
  sso:
    enabled: true
    clientId: # Required for sso configuration
      name: keycloak-oidc
      key: client-id
    clientSecret:
      name: keycloak-oidc
      key: secret-key
    scopes:
      - openid
      - profile
      - email
      - groups
    rbac:
      enabled: true
  extraArgs:
    - --auth-mode=client
    - --auth-mode=sso # Required for sso configuration
