workflow:
  serviceAccount:
    create: false
  rbac:
    create: false
server:
  ingress:
    enabled: true
    ingressClassName: 'nginx'
    pathType: ImplementationSpecific
  sso:
    enabled: true
    clientId: # Required for sso configuration
      name: keycloak-oidc
      key: ARGO_WORKFLOWS_CLIENT_ID
    clientSecret:
      name: keycloak-oidc
      key: ARGO_WORKFLOWS_CLIENT_SECRET
    scopes:
      - openid
      - profile
      - email
      - groups
    rbac:
      enabled: true
  extraArgs:
    - --auth-mode=client
    - --auth-mode=sso # Required for sso configuration
