apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: "8.0.14"
      helm:
        valueFiles:
          - $values/packages/argocd/values.yaml
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      ref: values
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      path: manifests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true