apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.17.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/packages/cert-manager/values.yaml
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      ref: values
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      path: packages/cert-manager/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
