apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-hub
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: "0.17.0"
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/packages/external-secrets/values.yaml
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true