apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: keycloak
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "24.7.3"
      helm:
        valueFiles:
          - $values/packages/keycloak/values.yaml
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      ref: values
    - repoURL: https://github.com/punkwalker/reference-implementation-aws
      targetRevision: ref-impl-v2
      path: packages/keycloak/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true