
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-env-vars
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: backstage-env-vars
    creationPolicy: "Merge"
    template:
      data:
        ARGOCD_AUTH_TOKEN: "argocd.token={{.ARGOCD_SESSION_TOKEN}}"
        POSTGRES_PASSWORD: "{{.password}}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "postgres-password"
  data:
  - secretKey: ARGOCD_SESSION_TOKEN
    remoteRef:
      conversionStrategy: Default # TODO: Remove when figured out how to avoid Diffs for CR defaults
      decodingStrategy: None
      metadataPolicy: None
      key: keycloak-clients
      property: ARGOCD_SESSION_TOKEN # Note: Read-Only non-expiring token
  - secretKey: BACKSTAGE_CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default # TODO: Remove when figured out how to avoid Drift for CR defaults
      decodingStrategy: None
      metadataPolicy: None
      key: keycloak-clients
      property: BACKSTAGE_CLIENT_SECRET
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  length: 48
  digits: 5
  symbols: 5
  symbolCharacters: "/-+"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: integrations
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: integrations
  data:
  - secretKey: "github-integration.yaml"
    remoteRef:
      conversionStrategy: Default # TODO: Remove when figured out how to avoid Diffs for CR defaults
      decodingStrategy: None
      key: cnoe-reference-implemntation-aws
      metadataPolicy: None
      property: backstage.github