apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: backstage
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.env.BACKSTAGE_FRONTEND_URL | quote }}
      secretName: backstage-prod-tls
  rules:
    - host: {{ .Values.env.BACKSTAGE_FRONTEND_URL | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage
                port:
                  number: 7007
