apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: backstage
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- if eq .Values.ingress.tls true }}
  tls:
    - hosts:
        - {{ .Values.env.BACKSTAGE_DOMAIN | quote }}
      secretName: backstage-server-tls
  {{- end }}
  rules:
    - host: {{ .Values.env.BACKSTAGE_DOMAIN | quote }}
      http:
        paths:
          - path: {{ default "/" .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: backstage
                port:
                  number: 7007
