{{- if .Values.postgresql.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "postgresql.fullname" . }}
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  serviceName: service-{{ include "postgresql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgresql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgresql.fullname" . }}
    spec:
      containers:
      - name: postgres
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: backstage-env-vars
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: postgress
  volumeClaimTemplates:
  - apiVersion: v1	
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "postgresql.fullname" . }}
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: {{ include "postgresql.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.env.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.postgresql.env.POSTGRES_DB | quote }}
{{- end }}