{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-all
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-read-all
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "backstage.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: read-all
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.argoWorkflows.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-argo-worfklows
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.argoWorkflows.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-argo-worfklows
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-argo-worfklows
subjects:
- kind: ServiceAccount
  name: {{ include "backstage.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}