# TODO: Seperate Backstage Secret and PostGres Secret.
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-env-vars
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20" # Create secret with static values from Helm values before external secret for dynamic values
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}
  BACKSTAGE_FRONTEND_URL: {{ .Values.env.BACKSTAGE_FRONTEND_URL | quote }}
  KEYCLOAK_NAME_METADATA: {{ .Values.env.KEYCLOAK_NAME_METADATA | quote }}
  ARGO_WORKFLOWS_URL: {{ .Values.env.ARGO_WORKFLOWS_URL | quote }}
  ARGO_CD_URL: {{ .Values.env.ARGO_CD_URL | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
stringData:
  k8s-config.yaml: |
    type: 'config'
    clusters:
      - url: https://kubernetes.default.svc.cluster.local
        name: local
        authProvider: 'serviceAccount'
        skipTLSVerify: true
        skipMetricsLookup: true
        serviceAccountToken: 
          $file: /var/run/secrets/kubernetes.io/serviceaccount/token
        caData: 
          $file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
