apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {{ .Values.namespace }}
  labels:
    app: backstage
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: {{ .Values.backstage.config.backend.listen.port }}
      targetPort: http