apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-cert
  namespace: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: default-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - advaitt.people.aws.dev # TODO: Find a way to substitute this