apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argocd
spec:
  generators:
    - scmProvider:
        cloneProtocol: https
        filters:
          - repositoryMatch: ^demo
            pathsExist: [kustomize/dev/kustomization.yaml]
        github:
          allBranches: false
          organization: ${GITHUB_ORG_NAME}
          tokenRef:
            key: password
            secretName: github-token
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{ repository }}'
    spec:
      destination:
        namespace: demo
        server: https://kubernetes.default.svc
      project: demo
      source:
        path: kustomize/dev
        repoURL: '{{ url }}'
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true

