apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: "https://github.com/cnoe-punkwalker/my-reference-implementation-aws.git"
  username: unused
  password: ""
