apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.12.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/packages/cert-manager/dev/values.yaml
    - repoURL: ${REPO_URL}
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
