apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.13.0
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/packages/external-dns/dev/values.yaml
        parameters:
          - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
            value: ${ROLE_ARN}
          - name: domainFilters[0]
            value: ${DOMAIN_NAME}
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
