apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: "0.9.2"
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/packages/external-secrets/dev/values.yaml
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
