apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.7.0
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/packages/ingress-nginx/dev/values.yaml
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
