apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "1.33"
  tags:
    githubRepo: "github.com/cnoe-io/reference-implementation-aws"
    env: "dev"
    project: "cnoe"
vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single
managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.large
    minSize: 3
    maxSize: 6
    desiredCapacity: 4
    volumeSize: 100
    ssh:
      allow: false
    labels:
      pool: system
addonsConfig:
  autoApplyPodIdentityAssociations: true
addons:
  - name: eks-pod-identity-agent
  - name: aws-ebs-csi-driver
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: ebs-csi-controller-sa
        wellKnownPolicies:
          ebsCSIController: true
iam:
  withOIDC: true
  podIdentityAssociations:
    - namespace: crossplane-system
      serviceAccountName: provider-aws
      permissionPolicyARNs:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      permissionsBoundaryARN: "${CROSSPLANE_BOUNDARY_POLICY_ARN}"
    - namespace: external-secrets
      serviceAccountName: external-secrets
      permissionPolicy:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "secretsmanager:ListSecrets"
              - "secretsmanager:BatchGetSecretValue"
            Effect: "Allow"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "secretsmanager:GetResourcePolicy"
              - "secretsmanager:GetSecretValue"
              - "secretsmanager:DescribeSecret"
              - "secretsmanager:ListSecretVersionIds"
            Resource:
              - "arn:aws:secretsmanager:us-west-2:${AWS_ACCOUNT_ID}:secret:cnoe-ref-impl/*"
    - namespace: kube-system
      serviceAccountName: aws-load-balancer-controller
      wellKnownPolicies:
        awsLoadBalancerController: true
    - namespace: external-dns
      serviceAccountName: external-dns
      wellKnownPolicies:
        externalDNS: true
