apiVersion: v1
kind: Namespace
metadata:
  name: data-on-eks
  labels:
    app: data-on-eks
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-on-eks
  namespace: data-on-eks
  labels:
    app: data-on-eks
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-on-eks
  namespace: data-on-eks
  labels:
    app: data-on-eks
subjects:
- kind: ServiceAccount
  name: data-on-eks
roleRef:
  kind: Role
  name: data-on-eks
  apiGroup: rbac.authorization.k8s.io

# allow for updating backstage config
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-on-eks
  namespace: backstage
  labels:
    app: data-on-eks
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "pods" ]
    verbs: [ "get", "patch" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-on-eks
  namespace: backstage
  labels:
    app: data-on-eks
subjects:
  - kind: ServiceAccount
    name: data-on-eks
    namespace: data-on-eks
roleRef:
  kind: Role
  name: data-on-eks
  apiGroup: rbac.authorization.k8s.io
