# This installs Addon AppSet chart on hub cluster so that the Addons can be managed from git
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-appset
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  destination:
    name: hub
    namespace: argocd
  sources:
    - repoURL: cnoe://
      targetRevision: HEAD
      path: "appset-chart"
      helm:
        valueFiles:
          - $values/bootstrap/appset-values.yaml
    - repoURL: cnoe://
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 