apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-appset
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: hub
    namespace: argocd
  sources:
    - repoURL: cnoe://appset-chart
      targetRevision: HEAD
      path: chart
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: cnoe://addons-appset
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 