apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hub
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: eks-krew
    namespace: argocd
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: "8.0.14"
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: cnoe://argocd
      targetRevision: HEAD
      ref: values
    - repoURL: cnoe://argocd
      targetRevision: HEAD
      path: manifests
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true