apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-in-cluster
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: eks-krew
    namespace: argocd
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: "8.0.14"
      helm:
        valueFiles:
          - $values/values.yaml
        ignoreMissingValueFiles: true
        releaseName: argocd
    - repoURL: cnoe://argo-cd
      targetRevision: HEAD
      ref: values
    - repoURL: cnoe://argo-cd
      targetRevision: HEAD
      path: manifests
  syncPolicy:
    automated:
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
    automated:
      selfHeal: true
      prune: true