apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-remote-reconcile
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: eks-krew
    namespace: argocd
  sources:
    - repoURL: cnoe://hub-addons
      targetRevision: HEAD
      path: "."
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true