apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-addons
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: eks-krew
    namespace: argocd
  sources:
    - repoURL: cnoe://hub-addons-appset
      targetRevision: HEAD
      path: chart
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: cnoe://hub-addons-appset
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true