installCRDs: true
global:
  leaderElection:
    namespace: cert-manager
extraObjects:
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: letsencrypt-prod
        solvers:
          - http01:
              ingress:
                ingressClassName: nginx
  - |
    {{ if eq .Values.global.pathRouting "true"}}
    # This resource is to create default certificate of the base domain
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: default-cert
      namespace: cert-manager
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      secretName: default-tls-prod
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      dnsNames:
      - {{ .Values.global.domainName }}
    {{ end }}
 